import type { ExperienceConfig, Experience } from "@/types/experience"
import { RAW_COMPONENTS } from "./raw-components"

export type FileMap = Record<string, string>

export function assembleProject(entry: Experience, config: ExperienceConfig): FileMap {
  const files: FileMap = {}

  // 1. Core Next.js boilerplate
  files["package.json"] = JSON.stringify({
    name: entry.manifest.id,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint"
    },
    dependencies: {
      "next": "16.2.10",
      "react": "19.2.4",
      "react-dom": "19.2.4",
      ...(entry.exporter.dependencies || {})
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^19",
      "@types/react-dom": "^19",
      "typescript": "^5",
      "tailwindcss": "^4.0.0",
      "@tailwindcss/postcss": "^4.0.0",
      "postcss": "^8.4.0"
    }
  }, null, 2)

  files["tsconfig.json"] = JSON.stringify({
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./*"] }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  }, null, 2)

  files["postcss.config.mjs"] = `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`

  files["next.config.ts"] = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;
`

  files["README.md"] = `# ${entry.manifest.name}

Built with:
• Next.js 16
• React 19
• Tailwind CSS v4

## Getting Started

Install dependencies:

\`\`\`bash
npm install
# or pnpm install / yarn / bun install
\`\`\`

Run the development server:

\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

## Project Structure

- \`app/\` — Next.js routes and layouts.
- \`components/\` — UI sections. Safe to modify freely.
- \`content/\` — All editable text, pricing, and data.
- \`public/\` — Static assets and images.

## Customizing

- **Content**: Edit \`content/home.ts\` to update text and links.
- **Design**: Edit \`app/globals.css\` to change theme colors and radius.
- **Layout**: Edit files inside \`components/\` directly.

## Deployment

Works immediately on:
- Vercel
- Netlify
- Any Node.js hosting

*Generated by ZenixUI — You own this code.*
\`

  files["REPORT.md"] = \`✓ Generated with ZenixUI

Framework
Next.js 16

Components
${entry.exporter.files.filter(f => f.endsWith(".tsx")).length}

Animations
${entry.exporter.files.filter(f => f.endsWith(".css")).length}

Dependencies
0 Internal (@zenix/ui)
${Object.keys(entry.exporter.dependencies || {}).length} External

Ready to deploy
npm install
npm run dev
npm run build
\`

  files[".gitignore"] = \`node_modules
.next
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local
`

  // 2. Next.js App Route & Layout
  files["app/layout.tsx"] = `import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "${entry.manifest.name}",
  description: "${entry.manifest.description}",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`

  // 3. Bake the Theme into globals.css
  const cssRadiusControl = config.theme.radius === "none" ? "0px" : config.theme.radius === "sm" ? "6px" : config.theme.radius === "md" ? "12px" : config.theme.radius === "lg" ? "20px" : "9999px"
  const cssRadiusCard = config.theme.radius === "none" ? "0px" : config.theme.radius === "sm" ? "12px" : config.theme.radius === "md" ? "20px" : config.theme.radius === "lg" ? "24px" : "32px"

  files["app/globals.css"] = `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
@import "tailwindcss";

@theme {
  --color-brand-primary: var(--brand-primary);
  --color-brand-secondary: var(--brand-secondary);
  --color-brand-foreground: var(--brand-foreground);
  
  --color-surface-bg: var(--surface-bg);
  --color-surface-card: var(--surface-card);
  --color-surface-elevated: var(--surface-elevated);
  --color-surface-border: var(--surface-border);
  
  --color-text-heading: var(--text-heading);
  --color-text-body: var(--text-body);
  --color-text-muted: var(--text-muted);
  --color-text-on-brand: var(--text-on-brand);
  
  --font-heading: var(--font-heading);
  --font-body: var(--font-body);
  
  --radius-control: var(--radius-control);
  --radius-card: var(--radius-card);
}

:root {
  --brand-primary:       ${config.theme.primaryColor};
  --brand-secondary:     ${config.theme.secondaryColor};
  --brand-foreground:    #ffffff;

  --surface-bg:          ${config.theme.backgroundColor};
  --surface-card:        ${config.theme.cardColor};
  --surface-elevated:    #1a1a1a;
  --surface-border:      ${config.theme.borderColor};

  --text-heading:        ${config.theme.headingColor};
  --text-body:           ${config.theme.bodyColor};
  --text-muted:          ${config.theme.mutedColor};
  --text-on-brand:       #ffffff;

  --font-heading:        '${config.theme.headingFont}', sans-serif;
  --font-body:           '${config.theme.bodyFont}', sans-serif;

  --radius-control:      ${cssRadiusControl};
  --radius-card:         ${cssRadiusCard};
}

html {
  -webkit-font-smoothing:  antialiased;
  -moz-osx-font-smoothing: grayscale;
  scroll-behavior:         smooth;
}

body {
  background-color: var(--surface-bg);
  color:            var(--text-body);
  font-family:      var(--font-body);
}

::-webkit-scrollbar { width: 6px; }
::-webkit-scrollbar-track { background: var(--surface-bg); }
::-webkit-scrollbar-thumb {
  background:    var(--surface-border);
  border-radius: 9999px;
}
::-webkit-scrollbar-thumb:hover { background: var(--text-muted); }
`

  // 4. Content file
  files["content/home.ts"] = `export const content: any = ${JSON.stringify(config.content, null, 2)}`

  // 5. Types
  if (RAW_COMPONENTS["types.ts"]) {
    files["types/index.ts"] = RAW_COMPONENTS["types.ts"].replace(/"@zenix\/ui"/g, '"@/types"')
  }

  // 6. Copy Sections using exporter capabilities
  for (const filePath of entry.exporter.files) {
    if (!RAW_COMPONENTS[filePath]) {
      console.warn(`[Assembler] File not found in RAW_COMPONENTS: ${filePath}`)
      continue
    }

    let code = RAW_COMPONENTS[filePath]
    // Fix imports inside sections
    code = code.replace(/from "\.\.\/types"/g, 'from "@/types"')
    code = code.replace(/from "\.\.\/\.\.\/types"/g, 'from "@/types"')
    code = code.replace(/from "\.\/components"/g, 'from "./index"')
    
    const relativePath = filePath.replace(`${entry.manifest.id}/`, "")
    if (!relativePath.includes("/")) {
      files[`components/${relativePath}`] = code
    } else {
      files[relativePath] = code
    }
  }

  // 7. Generate page.tsx using exporter capabilities
  files["app/page.tsx"] = entry.exporter.generatePage(config)

  return files
}
