import type { NavContent, HeroContent, CTAContent, ProofContent, ExploreContent, MakeItYoursContent, SocialProofContent } from "@zenix/ui"

export const navContent: NavContent = {
  logo: "Aurora.",
  links: [
    { label: "Platform", href: "#platform" },
    { label: "Models", href: "#models" },
    { label: "Safety", href: "#safety" },
    { label: "Company", href: "#company" },
  ],
  cta: { label: "Request Access", href: "#access" },
}

export const heroContent: HeroContent = {
  badge: "Aurora 2.0 is now available",
  headline: "Intelligence, refined.",
  subheadline: "Built for precise, deterministic reasoning.",
  primaryCta: { label: "Start building", href: "#build" },
  secondaryCta: { label: "Read the paper", href: "#paper" },
}

export const ctaContent: CTAContent = {
  headline: "Deploy intelligence.",
  subheadline: "Power the next generation of software.",
  primaryCta: { label: "Get started for free", href: "#start" },
  secondaryCta: { label: "Contact sales", href: "#sales" },
}

export const proofContent: ProofContent = {
  eyebrow: "Ownership",
  headline: "Engineered. Yours.",
  subheadline: "No proprietary runtime. What you see is exactly what exports.",
  items: [
    {
      title: "Clean React Export",
      description: "Idiomatic Next.js code.",
      visual: "folder",
    },
    {
      title: "Real, Editable Code",
      description: "No opaque abstractions.",
      visual: "code",
    },
    {
      title: "Modern Standards",
      description: "The stack developers trust.",
      visual: "checklist",
    }
  ]
}

export const exploreContent: ExploreContent = {
  eyebrow: "Starting Point",
  headline: "Experiences",
  subheadline: "Launch-ready foundations built with rigorous craftsmanship.",
  items: [
    { title: "Aurora", category: "AI Startup", status: "Live", href: "#aurora" },
    { title: "Kinetic", category: "Portfolio", status: "Live", href: "#kinetic" },
    { title: "Origin", category: "NGO", status: "Live", href: "#origin" },
    { title: "Savor", category: "Restaurant", status: "Live", href: "#savor" },
  ]
}

export const makeItYoursContent: MakeItYoursContent = {
  headline: "Make It Yours",
  subheadline: "Total ownership from the first click to the final commit.",
  items: [
    {
      title: "Customize",
      description: "Adapt theme, typography, and colors.",
      visual: "customize"
    },
    {
      title: "Own Every Line",
      description: "Export clean Next.js code.",
      visual: "export"
    },
    {
      title: "Continue Without Limits",
      description: "Open in VS Code and keep building.",
      visual: "continue"
    }
  ]
}

export const socialProofContent: SocialProofContent = {
  eyebrow: "The Standard",
  headline: "Built for engineers.",
  subheadline: "Feedback from developers who evaluate code quality.",
  quotes: [
    {
      quote: "I'd use this for my next client project. The code it exports is exactly how I would write it myself.",
      author: "Freelance Engineer",
      role: "Web Studio"
    },
    {
      quote: "Finally, a frontend tool that doesn't feel like a black box. The folder structure is perfect.",
      author: "Frontend Lead",
      role: "SaaS Startup"
    },
    {
      quote: "Clients always notice when a site looks like it was generated by AI. This feels handcrafted.",
      author: "Design Engineer",
      role: "Agency"
    }
  ]
}

export const content = {
  nav: navContent,
  hero: heroContent,
  proof: proofContent,
  explore: exploreContent,
  makeItYours: makeItYoursContent,
  socialProof: socialProofContent,
  cta: ctaContent
}
